### ISSUE TITLE
Remove VERSION

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-cli#106]
Redundant manual overhead.

Just check package.json instead, e.g. https://github.com/gruntjs/grunt-cli/blob/3254a1f36eb70d3cb106441c79ef4a16951e3011/bin/grunt#L34.

**Comment by chris-steele** [comment]
Done in https://github.com/adaptlearning/adapt-cli/pull/105/commits/9850358097d88ca78cab5924212d099b95439d42
