### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: invalid central directory file header signature

### ISSUE THREAD

**Issue by samumist** [adaptlearning/adapt-cli#108]
I just run into a problem with the `adapt-cli` version 2.1.5. When I run `adapt create course`, I’ve got an error (please see the attached screenshot). 

I use NVM on a MacOS 10.14.2. I tried the command in both Node 6 LTS and Node 8 LTS installed with nvm, same error. 

I've got the similar error on a Ubuntu 18.04 virtual machine with node 8.10.0 installed with `sudo apt`.

<img width="952" alt="screen-shot-2019-01-02-at-11 25 35-am" src="https://user-images.githubusercontent.com/3883086/50626417-0ddbc480-0f69-11e9-8444-eb230cbc1533.png">

`adapt install` does install the plugins inside a framework directly cloned from github.

**Comment by moloko** [comment]
hi @samumist just tried `adapt create course` on:
* macOS v10.14.2
* adapt-cli v2.1.5
* node v10.13.0

and all works OK

Could you give it a try with Node v10.x? We do recommend using the LTS version of Node - currently v10.15.0

**Comment by samumist** [comment]
Thanks @moloko !
I just tried with node v10.15.0 installed with nvm, the same error. It's really weird as I have almost exactly the same environment and it seems, apart from me, nobody has reported this problem.
<img width="1440" alt="screen shot 2019-01-07 at 11 25 30 am" src="https://user-images.githubusercontent.com/3883086/50747706-54cf0000-1270-11e9-833c-234ad4d8c905.png">

**Comment by moloko** [comment]
very odd. the error seems to be something vaguely to do with yauzl's inability to unzip a file, but that's about as far as I can get by searching on it.

**Comment by samumist** [comment]
yeah, that's really odd. I've tried on several different Macs, and all the same errors.

**Comment by samumist** [comment]
Today I tried again with a windows box, the same error.

Windows 10 Pro
Node 10.15.0 with nodist
Gitbash

![adapt_fail](https://user-images.githubusercontent.com/3883086/51370550-7e224280-1b32-11e9-9ac3-6b3b87f5332d.jpg)

**Comment by oliverfoster** [comment]
do you have git installed?

**Comment by chris-steele** [comment]
I thought it might be the yauzl library as I looked into this or a similar issue some time back but never reached a conclusion. The solution I have found is quite bizarre. Seems like listening to a `data` event (which doesn't seem to [exist](https://github.com/sindresorhus/got#streams-1)) causes the download to become corrupt (losing the first part of the buffer) - but only in certain environments. It was happening to me repeatedly on Linux. Really, really... odd!

Fix in https://github.com/adaptlearning/adapt-cli/pull/115

**Comment by samumist** [comment]
Thanks @chris-steele

**Comment by chris-steele** [comment]
@samumist excellent news and thank you for testing this. :+1:

**Comment by chris-steele** [comment]
Fixed in https://github.com/adaptlearning/adapt-cli/commit/c407eadbf287f48f600ca1b3f53d6d3ad7e28f83
