### ISSUE TITLE
create component command

### ISSUE THREAD

**Issue by cajones** [adaptlearning/adapt-cli#11]
GIven I am in a course directory when I run ```adapt create component``` it should download the template component from Github repo into the ```src/components/component-name``` directory.

GIven I am not in a course directory when I run ```adapt create component``` it should download the template component from Github repo into the ```component-name``` directory

**Comment by cajones** [comment]
GIven I am not in a course directory when I run adapt create component it should name the main js file, the css file and the templates file with the name of the component

**Comment by cajones** [comment]
GIven I am not in a course directory when I run adapt create component it should change the js src code to register the component by name.

**Comment by belal-almassri-spongeuk** [comment]
After typing adapt create component  in the console it asks for Confirm type, I tried true , y , Text etc.. What this suppose to be?

Thanks

**Comment by cajones** [comment]
supported in v0.0.19
