### ISSUE TITLE
adapt-register doesn't support the correct format of the repository property in bower.json

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#110]
as you can see from [the bower spec](https://github.com/bower/spec/blob/master/json.md#repository) the correct format for this property is:
```json
"repository": {
  "type": "git",
  "url": "git://github.com/foo/bar.git"
}
```
But the cli doesn't like this and requires it in the format:
```json
"repository": "git://github.com/foo/bar.git"
```
Which is confusing for anyone working to the standard as opposed to our slightly wonky take on the standard.

**Comment by chris-steele** [comment]
Fixed in https://github.com/adaptlearning/adapt-cli/commit/1bcd94ab70c25e187d7650cd93035b96fb3ceaa7
