### ISSUE TITLE
adapt-register not handling framework dependency properly

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#111]
When attempting to register a plugin where the framework dependency was specified in bower.json as `">=2" I received an "Invalid input for undefined" error. 

Eventually I was able to work around this by removing this property from bower.json and just accepting the default as prompted by the adapt-cli - but only after a certain amount of head-scratching!

![adapt-cli_register_fw_dep_issue](https://user-images.githubusercontent.com/1249597/53953619-ae667600-40cb-11e9-8135-4c54f7f1bd8c.png)

**Comment by chris-steele** [comment]
Fixed in https://github.com/adaptlearning/adapt-cli/commit/1bcd94ab70c25e187d7650cd93035b96fb3ceaa7
