### ISSUE TITLE
devinstall uses git protocol

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-cli#114]
Should probably switch to https for better cross environment compatibility.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-cli/blob/master/lib/promise/cloneInstall.js#L23

```js
var url = repoDetails.url.replace(/^git:\/\//, 'https://');
exec(`git clone ${url} "${pluginPath}"`);
```

**Comment by chris-steele** [comment]
Fixed in https://github.com/adaptlearning/adapt-cli/commit/e5a0eef98e9d5f6cd1e181e4a775eff634f96c1c
