### ISSUE TITLE
Error during registering a plug-in

### ISSUE THREAD

**Issue by kunjsharma** [adaptlearning/adapt-cli#117]
This issue was moved here from https://github.com/adaptlearning/adapt_framework/issues/2434 as suggested by @tomgreenfield

Subject of the issue/enhancement/features

While registering Adapt plug-in, an error coming.
Your environment

    Framework version 4.0.1
    Node 10.15.3
    npm 5.6.0
    Firefox 66.0.5
    Desktop PC + Windows 8

Steps to reproduce

when register a plug-in
Expected behaviour

It should register plug-in as I did it with other plugins.
Actual behaviour

Error occurred: TypeReeor: <source || "">.trim is not a function
Screenshots (if you can)

![ari](https://user-images.githubusercontent.com/6715520/57917056-92dcd000-78b1-11e9-8e0e-a91e06ac7d3c.png)

**Comment by kunjsharma** [comment]
Hi @NayanKhedkar re your response on this issue:  Yes, I notice when I run `$ adapt register` command, the text `"repository":" git://github.com/<user>/<repo_name>.git"` automatically changes into `"repository": { "type": "git", "url": "git://github.com/<user>/<repo_name>.git" }`. Is it any issue in adapt-cli or due to version of Node/npm I have?

**Comment by chris-steele** [comment]
@kunjsharma, @NayanKhedkar the latest version on npm should contain a fix for this as @tomgreenfield  mentions. I have now published a new release on GH that contains the same. Thanks for reporting.

**Comment by moloko** [comment]
Note that `"repository": { "type": "git", "url": "git://github.com/<user>/<repo_name>.git" }` is the correct format, according to [the documentation](https://github.com/bower/spec/blob/master/json.md#repository)

**Comment by kunjsharma** [comment]
Hi @chris-steele please close this issue if/when new release fixed this problem. The syntax `"repository":" git://github.com/<user>/<repo_name>.git"` worked with old version of node (tried on node-v6.11.1) though.
