### ISSUE TITLE
Default to latest tag

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-cli#125]
https://github.com/adaptlearning/adapt-cli/blob/2b667551ee2e58be98a16b13f7218643e5c2c095/lib/Constants.js#L16

Suggest this defaults to the latest tag (as per the authoring tool install script).

There have been issues cropping up recently where the unreleased framework wasn't playing ball with tagged plugins.

The only useful place for defaulting to `master` would be with the `devinstall` command.

**Comment by tomgreenfield** [comment]
Just to note that it'll need to be checked whether fetching the latest release via https://github.com/adaptlearning/adapt_framework/releases/latest or similar is suitable, or if we'd need to iterate through tags to get the _newest_ version number.

**Comment by chris-steele** [comment]
Should be fixed in v2.1.11 - all I did was take the suggested code from adapt_authoring - worked a treat ;-)
