### ISSUE TITLE
ignores branch/tag argument from cmd

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-cli#141]
The call to `highest()` at https://github.com/adaptlearning/adapt-cli/blob/d68d1e7083a3daeb5929f7ee81faf4b0a9e0218a/lib/commands/create.js#L18-L25 ignores the user's input of branch/tag stored in variable `branch` immediately before it.

To replicate:

1. Create a course with arguments as specified by README:
`adapt create course "My Course" legacy`  
2. The user is asked to confirm each argument provided except "leagacy". It is ignored and replaced by the highest tag.
![cli-bug](https://user-images.githubusercontent.com/9489014/111031131-0085b480-83d4-11eb-9a86-afdee624e20c.JPG)

**Comment by NayanKhedkar** [comment]
@chucklorenz [PR](https://github.com/adaptlearning/adapt-cli/pull/142) will fix it.
