### ISSUE TITLE
Authoring tool API + CLI Rewrite

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt-cli#148]
Have outlined below the kind of API we'd need from the AAT side :smile:

Function names/param naming & order are completely up for grabs, but should give an idea of what we need.

## Framework
The following API endpoints should only handle framework specific stuff (i.e. no plugin installs/updates).
```js
/**
 * Installs a clean copy of the framework
 * @param {String} version Specific version of the framework to install
 * @param {String} dir Directory to install into
 * @return {Promise}
 */
installFramework(version = "", dir)
/**
 * Updates the framework
 * @param {String} version Specific version of the framework to install
 * @param {String} dir Root path of the framework installation
 * @return {Promise}
 */
updateFramework(version = "", dir)
```
It would be great to be able to access the build tools from an API wrapper, with some nice errors etc. returned.
```js
/**
 * Runs the build for a current course
 * @param {String} dir Root path of the framework installation
 * @param {Object} options
 * @param {Boolean} options.devMode Whether to run the build in developer mode
 * @return {Promise}
 */
buildCourse(dir, options)
```
## Framework plugins
```js
/**
 * Installs a single framework plugin
 * @param {String} plugin Name of plugin (with optional version, e.g. @4.0.0 - defaults to the latest supported)
 * @param {String} dir Root path of the framework installation
 * @return {Promise} Resolves with the plugin's parsed bower JSON
 */
installPlugin(plugin = "", dir = process.cwd())
/**
 * Removes a single framework plugin
 * @param {String} plugin Name of plugin
 * @param {String} dir Root path of the framework installation
 * @return {Promise}
 */
uninstallPlugin(plugin, dir = process.cwd())
/**
 * Updates a single framework plugin
 * @param {String} plugin Name of plugin (with optional version, e.g. @4.0.0 - defaults to the latest supported)
 * @param {String} dir Root path of the framework installation
 * @return {Promise} Resolves with the plugin's parsed bower JSON
 */
updatePlugin(plugin = "", dir = process.cwd())
```
## Generic utilities
For clarity, the below could also be split into separate framework/plugin variants.
```js
/**
 * Retrieves all schema defined in the framework
 * @return {Promise} Resolves with array of JSON schema contents
 */
getSchemas()
/**
 * Loads a single JSON schema file by name
 * @param {String} name Name of the schema to load
 * @return {Promise} Resolves with JSON schema contents
 */
getSchema(name)
/**
 * Gets the update information for installed framework/plugins
 * @param {String} plugin Name of plugin (if not specified, all plugins are checked), should also accept 'adapt_framework'
 * @param {String} dir Root path of the framework installation
 * @return {Promise} Resolves with array/object with plugin update info (see below)
 */
getUpdateInfo(plugin = "", dir = process.cwd())
```
```js
/** 
 * @example return data for getUpdateInfo 
 */
[
  {
    "name": "adapt-contrib-accordion",
    "isManaged": false,
    "installedVersion": "4.0.0",
    "nextCompatibleVersion": "5.0.0",
    "latestVersion": "5.0.0"
  },
  {
    "name": "adapt-contrib-spoor",
    "isManaged": false,
    "installedVersion": "3.3.2",
    "nextCompatibleVersion": "3.3.2",
    "latestVersion": "3.3.2"
  },
  {
    "name": "adapt-custom",
    "isManaged": true,
    "installedVersion": "4.0.0",
    "nextCompatibleVersion": "5.0.0",
    "latestVersion": "5.0.0"
  }
]
```

**Comment by oliverfoster** [comment]
Awesome ta. Schemas?

**Comment by taylortom** [comment]
Regarding schemas: currently we have a glob that checks the current framework dir for `/**/schema/*.schema.json`, and register the matches in the json validator. We only store the schema name + path (altho we have to do a load upfront to make sure schema name + any extensions to other schemas are reigstered). We then load each schema fresh at the point of validation.

**Comment by oliverfoster** [comment]
I'd like it to at least initially load of the schemas for you, rather than by blob.

Secondarily and when the need arises to externalise it (possibly never). We can get the validation stuff out of the aat and make it a module. I don't think we have need on this side at the moment, but worth earmarking.

**Comment by taylortom** [comment]
Have updated the above. Happy to leave validation as is until (or indeed, if) we have a need for anything different.

**Comment by oliverfoster** [comment]
How does the new AAT install custom plugins currently?

**Comment by taylortom** [comment]
> How does the new AAT install custom plugins currently?

There's nothing in the CLI that deals with this kind of thing, so we just do the following: 
- Database entry added
- Zip contents is put in the framework, with a copy in a local 'data' folder
  -  Copy is used to restore the plugin if the framework folder is removed
  - Copy will also be likely used for situations where rolling back a borked update/install is needed

**Comment by taylortom** [comment]
@oliverfoster I've just realised I haven't planned for installing custom versions of the framework. We allow this in the current AAT by pulling in a git URL from the config file and cloning from that. I don't think we've ever made use of it at Kineo, but I know of others that have.

Not sure of the best way to do this, possibly just passing the URL as a third param to the `installFramework` function. 

It hopefully shouldn't impact any of the other functions, and I think we can be very strict with dealing with errors related to anything custom, so there shouldn't be any special behaviour there.

**Comment by oliverfoster** [comment]
I have the backend functions for that already made, so it should be quite straightforward. 👍 

https://github.com/adaptlearning/adapt-cli/blob/issue/148/lib/integration/AdaptFramework/downloadFrameworkBranchTo.js

https://github.com/adaptlearning/adapt-cli/blob/issue/148/lib/integration/AdaptFramework/cloneFrameworkBranchTo.js

**Comment by taylortom** [comment]
Wahoo, that's good news :smile: There's no rush to get this in immediately, but wanted to throw it out there

**Comment by oliverfoster** [comment]
getSchema perhaps redundant if getSchemas returns all schema contents
