### ISSUE TITLE
Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-cli#169]
Original issue https://github.com/adaptlearning/adapt-cli/pull/165
[error.txt](https://github.com/adaptlearning/adapt-cli/files/8769567/error.txt)
[issue.517-console.txt](https://github.com/adaptlearning/adapt-cli/files/8769569/issue.517-console.txt)
[issue517-terminal.txt](https://github.com/adaptlearning/adapt-cli/files/8769570/issue517-terminal.txt)

https://github.com/adaptlearning/adapt-cli/pull/165#issuecomment-1135915001
> @KristofferBroberg could you try to replicate your issue using the above changes?
> 
> I want to see what's in those stderr and error variable.

Tested:

`  source: null,
  stderr: 'Error: read ECONNRESET\n' +
    '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {\n' +
    '  errno: -54,\n' +
    "  code: 'ECONNRESET',\n" +
    "  syscall: 'read'\n" +
    '}\n' +`
   ...a bunch of NPM notices

From what I can tell/guess my installation is corrupt and @danielstorey's input is more relevant for this issue.

**Comment by taylortom** [comment]
The process.exit in econnreset.js is also causing the AAT to quit if there are any uncaught exceptions thrown by the app. 

Is there any way we can configure it to only run when in CLI mode?

**Comment by oliverfoster** [comment]
We can remove the process.exit and just have it log errors?
