### ISSUE TITLE
Updating the framework via the API causes all local plugins to be removed

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt-cli#185]
We get a complete fresh copy of the framework (including the adapt.json).

Can we add an option to the CLI that doesn't take the nuclear option, and preserves any installed plugins + the existing adapt.json?

Not sure if this counts as a bug or enhancement

**Comment by oliverfoster** [comment]
Of course

**Comment by oliverfoster** [comment]
* Add `updateFramework` function that preserves src/menu, src/extensions, src/components, src/theme and adapt.json
