### ISSUE TITLE
running adapt install in a non-adapt folder yields no feedback

### ISSUE THREAD

**Issue by cajones** [adaptlearning/adapt-cli#20]
it should say "hey this is not an adapt folder" or something

**Comment by dancgray** [comment]
Also running adapt install on a badly formatted adapt.json file yields no feedback. It just falls over silently.

**Comment by chris-steele** [comment]
Sounds like I'm not the only one who has left a trailing comma and been stumped as to what the problem is. Would be good to have some feedback +1

**Comment by oliverfoster** [comment]
+1 yup, you could use jsonhint/linter to parse all the config jsons before it begins? at least you'd get some human readable output with little effort?
