### ISSUE TITLE
Add required spawn parameter for Node on Windows

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-cli#211]
See https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

**Comment by oliverfoster** [comment]
Could you remember to link up your prs and issues correctly? You need to reference the issue from the pr `fix #[number]`, and add labels for 'bug' etc as well as assigning yourself to both the issue and the pr.

Here's a readme explaining: 
https://github.com/adaptlearning/adapt_framework/wiki/Git-flow#kanban-management

Closing as completed in https://github.com/adaptlearning/adapt-cli/pull/212
