### ISSUE TITLE
adapt create course from develop branch

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-cli#25]
When calling `adapt create course` and then choosing develop as branch I expect to have the course be entirely from develop branch i.e. framework, plugins, extensions, menu, theme etc.

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1, much needed feature for us...

**Comment by zenduo** [comment]
In the interim, could we not change the adapt.json file in the develop branch of the framework, modifying all the components, extensions entries from '*' to 'develop'? Then change over before releasing a new version?

**Comment by oliverfoster** [comment]
Yup, good plan.

**Comment by LukaszGrela** [comment]
Is it fixed and can be closed? or just the temp solution in place as @zenduo proposed?

**Comment by zenduo** [comment]
Think this is still open from what I know of the cli

**Comment by hrajotia** [comment]
As we have removed `develop` branch from framework/plugins repositories.. so this tickets does not make any sense.
