### ISSUE TITLE
version 0.23 not reported

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-cli#27]
The README says we're at v 0.23, yet 'adapt --version' is reporting 0.22. 
I was at v0.18. Updated with 'npm update -g adapt-cli'. Ran 'adapt --version'. Reported 0.22.

**Comment by hrajotia** [comment]
Hi, 
when you hit command like `npm install -g adapt-cli' it gets the code from http://www.npmjs.com/package/adapt-cli
currently the code is updated at github but @cajones needs to publish that on npmjs site.

**Comment by hrajotia** [comment]
Closing as its fixed now.
