### ISSUE TITLE
Adapt install doesn't install latest merges!! 

### ISSUE THREAD

**Issue by belal-almassri-spongeuk** [adaptlearning/adapt-cli#37]
I have installed a new adapt course (adapt create course master) from the master branch, compared the latest merges in the to the adapt-contrib-pageLevelProgress and I didn't find it in the course I just created. I ran adapt install on the course and didn't get the latest merges either, but when I changed the following line in adapt.json it worked for me:

        "adapt-contrib-pageLevelProgress": "*",
to 
        "adapt-contrib-pageLevelProgress": "master",

Any thoughts?

**Comment by oliverfoster** [comment]
We need to make a new release. See the tags page.

**Comment by belal-almassri-spongeuk** [comment]
This has been fixed.
