### ISSUE TITLE
Oh dear, something went wrong... Failed to read PLUGIN_NAME/.bower.json

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt-cli#44]
I get this error frequently when running `adapt install`. Running the command again usually works (sometimes requires multiple retries). 

Would be good to have the command try several times before exiting.

**Comment by taylortom** [comment]
![screen shot 2015-11-20 at 09 40 10](https://cloud.githubusercontent.com/assets/1059083/11296668/747895be-8f6b-11e5-920f-d6a3f7761c1b.png)

**Comment by chris-steele** [comment]
Apologies that this issue report was never actioned. A lot has changed with the install command since this was reported. Hopefully the problem you encountered has been resolved. Closing this issue, but if you still observe this behaviour please reopen.
