### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-cli#52]
README needs to be updated to reflect that the CLI is only intended for users working directly with the framework, rather than for use with the authoring tool.

**Comment by moloko** [comment]
The [updated README](https://github.com/chucklorenz/demo-wiki/wiki/adapt-cli-RDME) which @chucklorenz is working on covers this

**Comment by moloko** [comment]
![image](https://user-images.githubusercontent.com/1249597/92398015-ae5f9000-f11f-11ea-91d5-c4e0435b7681.png)
