### ISSUE TITLE
NPM dependencies that point to URLs 

### ISSUE THREAD

**Issue by ricksbrown** [adaptlearning/adapt-cli#53]
This in your `dependencies`: ["download": "git://github.com/adaptlearning/download.git"](https://github.com/adaptlearning/adapt-cli/blob/23f0add46fa9764d320a3597703e01c8da8c0530/package.json#L14) makes life very difficult in a secure enterprise environment behind a strict corporate firewall.

While we can point npm to a private (in-house) repository this does not affect dependencies that point to a URL instead of a package in npm. These sorts of requests are simply blocked and even if we could have them let them through the firewall we would have a dependency on  a cloud resource that we do not control and therefore not have truly repeatable builds.

This is a [terrible design decision](https://support.sonatype.com/hc/en-us/articles/213465048-Why-does-npm-client-need-access-to-URLs-other-than-my-private-registry-) on the behalf of npm itself, not actually your own issue, but it would be nice if you could find a way to avoid this sort of "non npm repository" dependency.

I raise this issue merely so you are aware of this impediment to users in strict corporate environments.

**Comment by oliverfoster** [comment]
fixed with adapt-cli@2.0.3 please confirm

**Comment by moloko** [comment]
closing due to lack of f/b
