### ISSUE TITLE
need ability to 'unregister' a plugin

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#57]
at the moment we've got a few that were accidentally registered with the wrong name that we now can't get rid of

**Comment by chris-steele** [comment]
In progress

**Comment by fraylopez** [comment]
Does @chris-steele unregister method works for non Collaborators?
I've been trying to unregister a package without luck. If that is the case, since I can register a package as contributor, it would make sense to be able to unregister it as well.

**Comment by chris-steele** [comment]
@fraylopez we've gone with the assumption that contributors are not necessarily trusted users, so I'm afraid to gain an unregistration a collaborator must be sought. I'll check in with the team on this and report back anything useful.

**Comment by oliverfoster** [comment]
Being a "collaborator" means that the only people nominated by the owner of a plugin have access to unregister it. Which is all fine and sensible.

The register functionality should likewise be limited to only "collaborators" of a project. However this isn't industry standard behaviour. NPM and Bower alike allow anyone to register a component, but only the owner of the registration to unregister it. As we are using github to do account management here... this logic follows the github account management system, allowing anyone to register and only the plugin "collaborators" to unregister (as opposed to the registration owner).

This is also how the bower community recommend managing the unregister calls as bower doesn't have account management either. https://bower.io/docs/creating-packages/

**Comment by fraylopez** [comment]
@oliverfoster Just to be clear, I've developed and registered the plugin I'd like to unregister (because of an error during registration where the plugin name isn't related to github endpoint).
By  collaborators I mean [this](https://www.adaptlearning.org/index.php/collaborators/) as opposite to "contributor" meaning someone who made a plugin and registered without being part of any "official" adapt team.

So, as far as I understand the next step would be to contact someone with "collaborator" role to ask to remove the package, is that right? Can someone point me on the right direction? Thanks!

**Comment by chris-steele** [comment]
@fraylopez yes I think I understand this, so you've registered a plugin that doesn't have a valid endpoint and now you can't unregister it? Just so I can confirm my understanding, what is the name of this plugin? I think if a plugin does not have a valid endpoint anyone should be allowed to unregister it, would you agree @oliverfoster ?

**Comment by oliverfoster** [comment]
I get what you meant by Collaborators, sorry, I read it with a small c, as in  'github collaborators'.

If you provide the details of the plugin you need to unregister then one of the core team should be able to unregister it. (And we can test Chris' new code! Woops).

I don't think anyone should be allowed to unregister invalid endpoints. It gets a bit messy with denial of service problems, like if github goes down, all the plugins would be invalid for the time it's offline, opening a window for anyone to have unregister rights - if that makes sense?

**Comment by chris-steele** [comment]
@oliverfoster yeah it'd have to only be allowed on a valid "GitHub is up but can't find this repo" API response. Anyway it's simpler to offer up an email address in the console for users to make a manual request to the framework collaborators if they want to unregister something but are not able, would you say? I think bower does a similar thing.

**Comment by chris-steele** [comment]
And, yes, please let us know what we can unregister for you! ;)

**Comment by fraylopez** [comment]
Thank you guys, the plugin I'm talking about is adapt-media-brightcove, uploaded last week by me. Once unregistered I'll try again. Keep the good work!

**Comment by chris-steele** [comment]
@fraylopez I've unregistered your plugin if you'd like to try again please?
