### ISSUE TITLE
'Invalid URL format' error on attempting to register a plugin

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#58]
![2016-12-15-10_11_39-cmder](https://cloud.githubusercontent.com/assets/1249597/21221485/72aa4ea2-c2b5-11e6-87e0-da5279fcfbe4.png)

Not a very helpful error as it gives you no clue as to what to do to rectify.

I've tried removing .git from the end of the URL, it still doesn't work

**Comment by moloko** [comment]
It's not just this plugin either, I get much the same when trying to register another:
![2016-12-19 14_32_06-cmder](https://cloud.githubusercontent.com/assets/1249597/21316299/fb400334-c5f7-11e6-8616-410d22e2e525.png)

**Comment by fabiobeoni** [comment]
Yes I can confirm the issue, same problem. Since my plugin name is "adapt-interactiveMap" I'm wondering if the problem can be related to the the issue #49 , since there is a already a plugin registered with the name "interactiveMovie".

**Comment by NayanKhedkar** [comment]
resolved-PR: https://github.com/adaptlearning/node-bower-server/pull/1

**Comment by fabiobeoni** [comment]
Anyone knows when the fixes will be released with a new version of the CLI, is there a plan? Thanks.

**Comment by chris-steele** [comment]
@fabiobeoni PR from @NayanKhedkar has been applied. Can you retry registering your plugin?

**Comment by NayanKhedkar** [comment]
@chris-steele  Done ! :+1:

**Comment by mediabounds** [comment]
I can confirm that I was able to register a plugin without receiving the "Invalid URL format" error.

**Comment by moloko** [comment]
is fine for me too now

**Comment by NayanKhedkar** [comment]
@moloko @chris-steele  i would like to inform you above issue has been replicating at my end.can you please  give a try and reopen it ?
please refer below screenshot.
![issue](https://user-images.githubusercontent.com/16237837/30576893-96595228-9d28-11e7-8a19-d9e911ae7204.png)

**Comment by chris-steele** [comment]
@NayanKhedkar I think it is because (as you [posted](https://github.com/adaptlearning/adapt-cli/issues/58#issuecomment-277584819) a while ago) you need to use the git:// scheme rather than https?

**Comment by NayanKhedkar** [comment]
@chris-steele  thanks! it's working 😃
