### ISSUE TITLE
adapt create component creates blank .js and .hbs files

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt-cli#59]
When I run the command the task executes without errors and the files are all downloaded but instead of replacing `componentName` with the specified name the files which are subject to this replace function are wiped, leaving blank bower, .js, .less and .hbs files

**Comment by moloko** [comment]
I just gave this a quick test - bower.json populated fine for me. 

I see what you mean about the main .js and .hbs files though

It looks from the [LESS template](https://github.com/adaptlearning/adapt-component/blob/master/less/componentName.less) file that it should actually be blank.

**Comment by danielstorey** [comment]
Yeah you're right - .less is blank anyway.

I've tracked the problem down as far as here:

[https://github.com/adaptlearning/adapt-cli/blob/develop/lib/promise/replaceTextContent.js#L8](https://github.com/adaptlearning/adapt-cli/blob/develop/lib/promise/replaceTextContent.js#L8)

**Comment by danielstorey** [comment]
Did anyone have the chance to check out PR #60 ?

**Comment by moloko** [comment]
hi @danielstorey apologies we've been struggling with the CLI side of things recently. We've now managed to get a handover how it all works so have a few people getting up to speed. I'll get someone to have a look soon.

**Comment by danielstorey** [comment]
No worries ;)

**Comment by chris-steele** [comment]
@danielstorey, thanks for looking into this. Just reviewing this now, and, frustratingly(!), I can't replicate the original issue in either Windows cmd.exe, Windoes PowerShell or MinGW with a variety of component names. Can you tell me what OS/shell you are using and the exact command?

**Comment by danielstorey** [comment]
Just using cmd.exe in windows 10. Node v 4.4.7.

I couldn't work out exactly why reading the file after writing would solve
the problem but it did. Maybe something to do with the file not being
closed/saved properly after opening for writing, which performing a read
action triggers.

**Comment by chris-steele** [comment]
@danielstorey yeah looking at the original code I can't see why this would fail. From your PR it looks like you're using the latest adapt-cli, but can I just get you to double check this. In particular, could you run `npm update -g adapt-cli` to ensure you have the latest dependencies and then see if the bug is still replicable?

**Comment by moloko** [comment]
@danielstorey just been trying this again on a screenshare with @chris-steele and it's now working for me... BUT what we did figure out is that when I originally tried I was running an older version of adapt-cli (v2.0.2 I think). Since then I have updated to v2.0.4

Could you just let us know what version you are running by doing `$ adapt --version`?

**Comment by danielstorey** [comment]
Yup, I was on 2.0.2. Just updated and it's working now! The only thing I
would mention is I also modified lib/commands/create/component.js
<https://github.com/adaptlearning/adapt-cli/pull/60/commits/87930a9230cf385c5da5b04a619f99c285eed041#diff-5796c406d07932a291b2fddcfcb0d5cc>
to
prefix the folder name with adapt-
<https://github.com/adaptlearning/adapt-cli/pull/60/commits/87930a9230cf385c5da5b04a619f99c285eed041#diff-5796c406d07932a291b2fddcfcb0d5cc>
and
also change any instances of ComponentName
<https://github.com/adaptlearning/adapt-cli/pull/60/commits/87930a9230cf385c5da5b04a619f99c285eed041#diff-5796c406d07932a291b2fddcfcb0d5cc>
with
the Pascal'd user-defined name as found in the .js file. These of course
are aesthetic changes and everything still works without them so I'll leave
this for your consideration.

On another note is it worth merging the
https://github.com/adaptlearning/adapt-component develop branch into the
master as the _isResetOnRevisit check is quite useful?

Cheers guys :)

**Comment by chris-steele** [comment]
@danielstorey certainly valid for consideration :) So, the question is whether we want to enforce a naming convention when creating components through the CLI. Although it could be circumvented by creating components manually, it is nevertheless a good idea. We'd probably want the same for other plugin types (extension, menu, theme) and perhaps only allow bower registration if the plugin follows the convention. This is probably something to through open to the wider community. @moloko, would you say?

As for the _isResetOnRevisit, you're probably right, it would be beneficial to include this update. Would you mind creating a separate PR with this change and we can get that reviewed and merged hopefully?
