### ISSUE TITLE
feature request: ability to update plugins via the CLI

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#61]
In an ideal world, we'd have something like:
```
adapt update all
adapt update plugin-name
adapt update components
adapt update extensions
adapt update menus
adapt update themes
```
Or possibly even combinations e.g. `adapt update components extensions`

**Comment by chris-steele** [comment]
Most of the time plugins have a semver of '*', but in cases where a specific version/range has been requested the latest version of the plugin must satisfy the semver to be updated. In this case the user will be notified, but no action will be taken. Is that a correct assumption?

**Comment by oliverfoster** [comment]
i imagine if we did adapt update plugin-name@specificversionnumber if should take action? or should the override to a previous install be another install?

**Comment by chris-steele** [comment]
@moloko what are your thoughts?

**Comment by moloko** [comment]
OK so my main reason for logging this was that at the moment - unless I'm very mistaken - there's no way of forcing my install of adapt to update plugins to the latest version should new releases be available... at least not without deleting that plugin then running `$ adapt install` again.

So, I just want the CLI to allow for a user to able to update a plugin/all plugins/group of plugins...

I think being able to install a specific version of a plugin is less of a priority...  presumably a user could do this by specifying the version number in adapt.json??

**Comment by chris-steele** [comment]
Thanks both, OK so my reading of the requirement when running `adapt update`, in reference to `adapt.json` is:
- if plugin version specified as '*' then update
- else if range specified and update within specified range available then update
- else if range specified and no update within range then prompt user to update to latest or not
- else if specific version specified then prompt user to update to latest or not

The above assumes the command is `adapt update [all|components|extensions|menus|themes|plugin-name]`

If the command is `adapt update plugin-name#version` then update plugin to requested version.

Sound good?

**Comment by oliverfoster** [comment]
``adapt update plugin-name#version`` would be update and fix at that version (write to adapt.json)?

**Comment by chris-steele** [comment]
@oliverfoster yep, think that would be logical, agreed?

**Comment by chris-steele** [comment]
We need an **inprogress** label. Consider this **inprogress**....

**Comment by moloko** [comment]
@chris-steele any movement on this?

**Comment by chris-steele** [comment]
Command ready for testing. Please see https://github.com/chris-steele/adapt-cli/blob/develop/TESTING.md
