### ISSUE TITLE
Plugin Browser missing description for plugin

### ISSUE THREAD

**Issue by mediabounds** [adaptlearning/adapt-cli#62]
I registered a couple of plugins yesterday and they are both now appearing in the [Plugin Browser](https://www.adaptlearning.org/index.php/plugin-browser/):
* adapt-fastclick
* adapt-detailed-feedback

When I click on *adapt-detailed-feedback*, it displays the contents of the Readme file from GitHub. However, clicking on *adapt-fastclick* does not display the contents of the Readme file.

I suspect this is because the `url` I used when registering these two plugins was a little different. For *adapt-detailed-feedback*, I used:
```git://github.com/gowithfloat/adapt-detailed-feedback.git```

But for *adapt-fastclick*, I used (missing `.git` at the end):
```git://github.com/gowithfloat/adapt-fastclick```

How can I adjust the record for *adapt-fastclick* to display the Readme?

**Comment by moloko** [comment]
@mediabounds I think it may be more to do with the fact that you've called your readme file ReadMe.md rather than README.md

**Comment by mediabounds** [comment]
Yep--looks like that did it. Thanks!
