### ISSUE TITLE
Plugin can't be found in repository

### ISSUE THREAD

**Issue by mediabounds** [adaptlearning/adapt-cli#63]
Yesterday, I registered a "adapt-next-button" component to the repository, but it never showed up in the [Plugin Browser](https://www.adaptlearning.org/index.php/plugin-browser/).

I tried searching for it using the CLI, but I could not find it.
```
dpfeiffer:adapt-next-button dpfeiffer$ adapt search next
no plugins found adapt-next
dpfeiffer:adapt-next-button dpfeiffer$ adapt search next-button
no plugins found adapt-next-button
dpfeiffer:adapt-next-button dpfeiffer$ adapt search | grep next
dpfeiffer:adapt-next-button dpfeiffer$
```

Thinking that maybe the registration process failed, I tried to call `adapt register` again, but this time got:
```Error: Duplicate package```

**Comment by chris-steele** [comment]
Hi @mediabounds, I can't see anything in the database at present. Would you mind trying to register this again? Please let me know when you try so that I can view the logs to troubleshoot what is happening.

**Comment by mediabounds** [comment]
Hi, @chris-steele -- I am receiving the same error when I try to register:
```
dpfeiffer:adapt-next-button dpfeiffer$ adapt register
This will publish this plugin to https://bower.herokuapp.com
Confirm name  (adapt-next-button) 
Confirm repository  (git://github.com/gowithfloat/adapt-next-button.git) 
Confirm framework  (^2.0.0) 
Confirm Register now?  (y) 
Error: Duplicate package
```

**Comment by chris-steele** [comment]
I think you're missing the .bowerrc file (have a quick look here: https://github.com/adaptlearning/adapt_framework/wiki/Registering-a-plugin). You just need to copy it from somewhere like [this](https://github.com/adaptlearning/adapt_framework/blob/master/.bowerrc).

**Comment by mediabounds** [comment]
Bah. You are right. Totally overlooked that. Thank you!
