### ISSUE TITLE
unable to install adapt-cli due to nodegit package

### ISSUE THREAD

**Issue by joyabbhi** [adaptlearning/adapt-cli#67]
below is the log. Thanks for looking into this.

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/root/.nvm/versions/node/v4.2.6/bin/node" "/root/.nvm/versions/node/v4.2.6/bin/npm" "install" "-g" "adapt-cli"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by moloko** [comment]
have you tried installing nodejs-legacy? that has [worked for others](https://community.adaptlearning.org/mod/forum/discuss.php?d=1769#p8063).

**Comment by moloko** [comment]
@joyabbhi any update?

**Comment by jcastrillo** [comment]
I follow the steps trying to solve this problem but change to that:

root@ip-172-31-34-186:/home/ubuntu# npm install -g adapt-cli
|
> nodegit@0.16.0 install /root/.nvm/versions/node/v4.2.6/lib/node_modules/adapt-cli/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v4.2.6/lib/node_modules/adapt-cli/node_modules/nodegit/lifecycleScripts/preinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/root/.nvm/versions/node/v4.2.6/bin/node" "/root/.nvm/versions/node/v4.2.6/bin/npm" "install" "-g" "adapt-cli"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

I dont know what to do!

**Comment by joyabbhi** [comment]
@moloko : Yes, it worked for me. Thanks for the right direction.

**Comment by moloko** [comment]
reopening because @jcastrillo is still having problems

**Comment by jcastrillo** [comment]
hi @moloko thank u. After many attemps i decide to follow the process of the installation with out root user. And now its work. Not use "sudo su"

**Comment by moloko** [comment]
@jcastrillo interesting, useful info. thanks for sharing.

**Comment by toeknee581** [comment]
installing nodejs-legacy worked for me too.

**Comment by mantriv** [comment]
Hi,
I am trying to install adapt-cli but not able to install.

Find below the error log:
D:\>npm install -g adapt-cli
C:\Users\...\AppData\Roaming\npm\adapt -> C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\bin\adapt

> nodegit@0.16.0 install C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp

ERR! configure error

gyp
ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp
ERR! stack     at PythonFinder.failNoPython (C:\Users\....\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR!
stack     at PythonFinder.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack
at C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR!
stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp
ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\nodegit\\build\\Release"
gyp ERR! cwd C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp
ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\...\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
C:\Users\...\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "adapt-cli"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\...\Projects\GRCNinja\Docs\adapt\adapt_authoring\npm-debug.log
npm ERR! code 1

**Comment by moloko** [comment]
hi @mantriv I see from the above that you are using node 7.10.0 - but if you look at the authoring tool installation instructions it does say to use the node LTS version (currently 6.11.3), please could you switch to that version and try again?

**Comment by mantriv** [comment]
Thanks, after installing Node 6.11.3 I am able to run the application locally. Thanks again!
But now I am not sure how to get the login and password because as per the documentation step 3 
"npm install", need to provide the email address and password for super user but this step didnt ask any question / input. Only next step "node install" ask the questions / input that too for SMTP and not the super user. 
Please advise, how to setup the credentials to login to the application locally.
Thanks.

**Comment by moloko** [comment]
@mantriv no problem - actually useful to know that it didn't work with node v7; that's going to become the LTS release for Node in just a few days time so I guess we need to do a bit of testing against that version!

**Comment by samuel11235** [comment]
hi I have been trying to download adapt-cli but I have some errors, your saying that node 6.11.3  version is a good version to download but on the website its only shows node 8.10.0 lTS  and  the current version. So which one is suitable to use?  and there is no node.version 6.11.3 on the actual site for downloading node.js.

**Comment by moloko** [comment]
@samuel11235 there's an 'other downloads' link on that page...

**Comment by moloko** [comment]
@samuel11235 equally if you Google 'node 6.1.1.3 download' the first search result is the 'previous releases' page for Node.

**Comment by samuel11235** [comment]
hi which node.js are we supposed to use,  I got errors when downloading adapt cli, does the current one work which is 8.10.0 LTS ?

**Comment by moloko** [comment]
yes it does. 

if you have further issues/questions then - rather than replying to a closed issue - could you post in either the forums or adapt-cli gitter chat room, providing details of what platform you're on, what you've done so far and what issues you're getting?
