### ISSUE TITLE
adapt version

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-cli#69]
this currently only displays the version of the cli. it probably should also display the framework version from the package.json if available.

perhaps like:
```
$ adapt version
CLI: x.x.x
Framework: x.x.x
```

**Comment by canstudios-louisem** [comment]
Would be nice if it also gave the authoring tool version along with the tool's framework version if you are in the root a tool install.

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-cli/pull/90
