### ISSUE TITLE
npm install of nodegit fails saying: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Doutre** [adaptlearning/adapt-cli#84]
installed adapt on linux 64bit and everything is working fine.  when i tried to add additional themes/extensions/components i got a similar msg, attempted to re-install nodegit and adapt-cli, but am getting failures like:
[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node "/root/GitHub/adapt_authoring/node_modules/nodegit/dist/nodegit.js"
/root/GitHub/adapt_authoring/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^
Yes, I have /usr/include/gcrypt.h (libgcrypt-1.5.6-x86_64)

Suggestions?

**Comment by moloko** [comment]
hi @Doutre - bit unclear as to what the issue is and what you are trying to do. The path you have pasted suggests you are working with the authoring tool, in which case you'll better off asking about this in the [forums](https://community.adaptlearning.org/mod/forum/view.php?id=4) or in the [chat room](https://gitter.im/adaptlearning/adapt_framework)

**Comment by Doutre** [comment]
I was installing the Adapt server and testing.  Not sure whether I did the install correctly as I was using the generic Linux instructions.  Things work, mostly, but those error msgs are worrisome and I suspect there may be a version problem.  
For Adapt framework 2.2.5,  I used the latest 
Node.js version 6.12.3, 
npm version 3.10.10, 
MongoDB (community edition) version 3.6.2 
and am running on a 64bit-only Linux 3.2.98 (kernel) and the error is coming from curl-7.58.0-x86_64 (libcurl-gnu-tls).  Should this work or should other versions be tried, or?

**Comment by oliverfoster** [comment]
Linux 64bit is not an operating system. Please include the full name and version number of the operating system and device you are using. There are huge differences in environments, package management systems, supported libraries, environment variables etc.

Are you are sure the issue you are having relates directly to this repository? If so could you please include a full screenshot or log of the error you are receiving and the commands you attempted, as well as a description of how you think it relates to this repository.

At the moment the only thing that is clear from the information you have provided, is that you are trying to install the Adapt Authoring Tool and this is entirely the wrong place to ask for help do that.

You might have more success following @moloko's directions and seeking help in a more appropriate place.

**Comment by Doutre** [comment]
Slackware Linux 14.0 64-bit (with some custom re-compiles of a few packages).  Running on a dual quad-core, 16 GB RAM Lenovo ThinkCentre M91P.
root@Edd501:~/GitHub/adapt_authoring# uname -a
Linux Edd501 3.2.98 #2 SMP Thu Jan 11 16:18:36 CST 2018 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux

root@Edd501:~/GitHub/adapt_authoring# npm install -g nodegit

> nodegit@0.20.3 install /usr/lib/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/usr/lib/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.20.3 postinstall /usr/lib/node_modules/nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node "/usr/lib/node_modules/nodegit/dist/nodegit.js"
/usr/lib/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/usr/lib/node_modules/nodegit/dist/nodegit.js"' }
/usr/lib
`-- nodegit@0.20.3
  `-- node-gyp@3.6.2
    `-- minimatch@3.0.4
      `-- brace-expansion@1.1.9
root@Edd501:~/GitHub/adapt_authoring#

Since I am getting build/postinstall errors, it seems logical to ask these questions here.

**Comment by Doutre** [comment]
btw, the whole reason I was trying to re-install nodegit was due to errors when trying to run the adapt CLI to install template/modules/etc.   e.g.
root@Edd501:~/GitHub/adapt_authoring# adapt ls
/usr/lib/node_modules/adapt-cli/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/adapt-cli/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/adapt-cli/lib/promise/cloneInstall.js:6:15)
root@Edd501:~/GitHub/adapt_authoring#

Following some of the advice in the forums I was trying to re-install some parts to fix the problems.

**Comment by Doutre** [comment]
Before somebody asks the next obvious question, yes I have plenty of available disk space:
root@Edd501:~/GitHub/adapt_authoring# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       464G  100G  365G  22% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
root@Edd501:~/GitHub/adapt_authoring#

**Comment by oliverfoster** [comment]
Slackware doesn't provide a package containing or providing libcurl-gnutls:
https://packages.slackware.com/?search=curl

Fedora does:
https://apps.fedoraproject.org/packages/s/curl

Ubuntu does:
https://packages.ubuntu.com/search?keywords=curl&searchon=names&suite=artful&section=all

Arch does:
https://www.archlinux.org/packages/?sort=&q=curl&maintainer=&flagged=

Please either compile the library and it's dependencies or use an operating system that can install nodegit.

**Comment by Doutre** [comment]
Well, that does answer my question as to what the problem is.  Thanks.

**Comment by oliverfoster** [comment]
if `/usr/lib64/libcurl.so.4` exists, you can:
```sh
$ sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
```

**Comment by thepont** [comment]
On Arch Linux install the `libcurl-gnutils` package.

`sudo pacman -S libcurl-gnutls`
