### ISSUE TITLE
adapt install command should only run in an adapt folder

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#89]
the `adapt install` command will quite happily run from wherever it is called when it really it should check that it's in an Adapt folder first (suggest checking for presence of adapt.json in the current directory) and, if not found, show an error and halt.

**Comment by chris-steele** [comment]
I think @NayanKhedkar is looking into this.

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-cli/pull/91

**Comment by moloko** [comment]
done in db7942b4734d8e184b36cf425c10857ee6b741ab
