### ISSUE TITLE
Support creating a course via tag not just branch

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt-cli#92]
Sometimes you want to create a course using a specific version of the framework.

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-cli/pull/109

**Comment by NayanKhedkar** [comment]
![create_course](https://user-images.githubusercontent.com/16237837/51729842-546d9c00-209b-11e9-8b91-84683270f532.png)

**Comment by moloko** [comment]
Great stuff @NayanKhedkar thanks for picking this up!
