### ISSUE TITLE
next version

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-cli#95]
Ran `$ adapt update all` twice:

![image](https://user-images.githubusercontent.com/7974663/43454403-d38687ea-94b4-11e8-8cdb-2add579d2718.png)

![image](https://user-images.githubusercontent.com/7974663/43454291-6bb4f534-94b4-11e8-9e5b-150fe2fc2be9.png)

`adapt-contrib-spoor from 3.0.3 to 3.0.2 (latest is 3.0.2)` < weird
`adapt-contrib-trickle from 2.2.1 to 2.3.1 (latest is 2.3.1)` < why no upgrade?

**Comment by chris-steele** [comment]
@oliverfoster spoor is due to 3.0.3 being unreleased, but the trickle one is odd - any possibility you can wing me your src folder as it was when you ran the command?

**Comment by oliverfoster** [comment]
I have sent you a teams message.

**Comment by moloko** [comment]
and it seems like the trickle one is my fault too..

**Comment by moloko** [comment]
I think this can be closed, seems to me it's merely struggling to deal with my cockups ;-)
