### ISSUE TITLE
adapt create course plugin installation process is confusing when installing legacy branch

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-cli#97]
the new feature that tries to find more up-to-date versions of plugins that are still compatible is a bit confusing (on Windows, anyway) due to the way the prompts are presented - when I first encountered this I thought the install had failed.

When I tried again I realised it was just giving me prompts about newer versions of plugins being available (all the ones in question still function with the legacy branch but haven't been listed in legacy's adapt.json as they don't have IE8 support anymore) - but it's very hard to read the prompts - had I not known already what to do I would have struggled to get through this - even then I messed it up a bit on the first try because I didn't realise that the default choice if you just press `<enter>` is 'skip'...

The screenshot below gives you some idea of how confusing it looks
![adapt-cli-legacy](https://user-images.githubusercontent.com/1249597/47224036-80012c00-d3b2-11e8-83bd-a614f1ae7cbb.png)

Other than changing the default choice for pressing `<enter>` to 'requested version', I'm not sure what we might do to improve this.

Logging this partly for reference in case anyone else runs into this.

**Comment by chris-steele** [comment]
@moloko yeah certainly going on your screenshot the output looks rather messed up. I haven't seen that `sill install printInstalled` stuff before. Can you let me know what command you ran and what your Adapt folder was like (if you can remember!).

**Comment by moloko** [comment]
from what I remember I was just doing `adapt create course legacy-test legacy`. 

I have a feeling [this change](https://github.com/adaptlearning/adapt_framework/commit/ceb39197b4f8f01d4a68fcbf9f8d94dffab77ed1#diff-6f3071d8dfcfcba74eaa6356101e4678) will prevent anyone trying to install FW v2.2.7 or later from seeing this issue

**Comment by moloko** [comment]
closing this as hardly anyone uses the legacy branch now
